---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: node-app-deployment
  namespace: default
  labels:
    app: node-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: node-app
  template:
    metadata:
      labels:
        app: node-app
    spec:
      terminationGracePeriodSeconds: 30
      containers:
      - name: node-app
        image: 'gcr.io/logics-2-0-nonprod/node-app:latest'
        imagePullPolicy: "Always"
        ports:
        - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: node-app-svc
  namespace: default
  annotations:
    cloud.google.com/load-balancer-type: Internal
  labels:
    app: jenkins
spec:
  type: LoadBalancer
  loadBalancerIP: null
  loadBalancerSourceRanges: null
  ports:
    - port: 80
      targetPort: 8080
      protocol: TCP
  selector:
    app: node-app
