---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: app-hello-world
  namespace: default
  labels:
    app: app-hello-world
    version: blue
spec:
  replicas: 1
  selector:
    matchLabels:
      app: app-hello-world
  template:
    metadata:
      labels:
        app: app-hello-world
    spec:
      containers:
      - name: app-hello-world-ctr
        image: gcr.io/quantum-talent-301321/cmb-demo:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 3000
---
apiVersion: v1
kind: Service 
metadata:
  name: app-hello-world-svc
  namespace: default
  labels:
    app: app-hello-world
spec:
  selector:
    app: app-hello-world
    version: blue
  type: LoadBalancer 
  ports:
    - port: 3000
      targetPort: 3000
      protocol: TCP
