---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: node-app-deployment
  namespace: default
  labels:
    app: node-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: node-app
  template:
    metadata:
      labels:
        app: node-app
    spec:
      terminationGracePeriodSeconds: 30
      containers:
      - name: node-app-ctr
        image: gcr.io/quantum-talent-301321/cmb-demo:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 3000
---
apiVersion: v1
kind: Service 
metadata:
  name: node-app-svc
  namespace: default
  labels:
    app: node-app
spec:
  type: LoadBalancer 
  ports:
    - port: 80
      targetPort: 3000
      protocol: TCP
  selector:
    app: node-app
